python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_480/data/FB15k-237/test_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_480/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_480 --output_file test_data.txt --model Complex --entity_map --relation_map --filter --predictions --scores
python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_480/data/FB15k-237/validation_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_480/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_480 --output_file validation_data.txt --model Complex --filter_val --predictions --scores_val
python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_480/data/FB15k-237/train_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_480/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_480 --output_file train_data.txt --model Complex --predictions
python3 tokenize_pkl.py --inp closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_480/mapped_to_ids/entity_id_map.txt --model_str bert-base-cased
python3 tokenize_pkl.py --inp closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_480/mapped_to_ids/relation_id_map.txt --model_str bert-base-cased

python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_960/data/FB15k-237/test_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_960/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_960 --output_file test_data.txt --model Complex --entity_map --relation_map --filter --predictions --scores
python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_960/data/FB15k-237/validation_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_960/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_960 --output_file validation_data.txt --model Complex --filter_val --predictions --scores_val
python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_960/data/FB15k-237/train_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_960/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_960 --output_file train_data.txt --model Complex --predictions
python3 tokenize_pkl.py --inp closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_960/mapped_to_ids/entity_id_map.txt --model_str bert-base-cased
python3 tokenize_pkl.py --inp closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_960/mapped_to_ids/relation_id_map.txt --model_str bert-base-cased

python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_1440/data/FB15k-237/test_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_1440/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_1440 --output_file test_data.txt --model Complex --entity_map --relation_map --filter --predictions --scores
python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_1440/data/FB15k-237/validation_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_1440/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_1440 --output_file validation_data.txt --model Complex --filter_val --predictions --scores_val
python convert_kbc.py --kge_output closed_kbc_data/yatin-incremental-training/mb_1440/data/FB15k-237/train_data.pkl --kbe_data_dir closed_kbc_data/kg-bert --kge_data_dir closed_kbc_data/yatin-incremental-training/mb_1440/ --dataset FB15k-237 --output_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_1440 --output_file train_data.txt --model Complex --predictions
python3 tokenize_pkl.py --inp closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_1440/mapped_to_ids/entity_id_map.txt --model_str bert-base-cased
python3 tokenize_pkl.py --inp closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_1440/mapped_to_ids/relation_id_map.txt --model_str bert-base-cased


CUDA_VISIBLE_DEVICES=2 python run.py --save models/yatin_incremental/mb_480 --mode train_test --gpus 1 --epochs 20 --stage2 --negative_samples 10 --data_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_480 --model mcq --stage1_model Complex --model_str bert-base-cased --task_type both --max_tokens 5000 --ckbc

CUDA_VISIBLE_DEVICES=3 python run.py --save models/yatin_incremental/mb_960 --mode train_test --gpus 1 --epochs 20 --stage2 --negative_samples 10 --data_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_960 --model mcq --stage1_model Complex --model_str bert-base-cased --task_type both --max_tokens 5000 --ckbc

CUDA_VISIBLE_DEVICES=4 python run.py --save models/yatin_incremental/mb_1440 --mode train_test --gpus 1 --epochs 20 --stage2 --negative_samples 10 --data_dir closed_kbc_data/data_for_stage2/yatin-incremental-training/mb_1440 --model mcq --stage1_model Complex --model_str bert-base-cased --task_type both --max_tokens 5000 --ckbc




python convert_kbc.py --kge_output ~/mayank/closed_kbc_data/ConvE-complex/data/FB15k-237/test_data.pkl --kbe_data_dir ~/mayank/closed_kbc_data/kg-bert --kge_data_dir ~/mayank/closed_kbc_data/ConvE-complex/ --dataset FB15k-237 --output_dir ~/mayank/closed_kbc_data/data_for_stage2/ConvE-complex-fb15k237 --output_file test_data.txt --model Complex --entity_map --relation_map --filter --predictions --scores
python convert_kbc.py --kge_output ~/mayank/closed_kbc_data/ConvE-complex/data/FB15k-237/validation_data.pkl --kbe_data_dir ~/mayank/closed_kbc_data/kg-bert --kge_data_dir ~/mayank/closed_kbc_data/ConvE-complex/ --dataset FB15k-237 --output_dir ~/mayank/closed_kbc_data/data_for_stage2/ConvE-complex-fb15k237 --output_file validation_data.txt --model Complex --filter_val --predictions --scores_val
python convert_kbc.py --kge_output ~/mayank/closed_kbc_data/ConvE-complex/data/FB15k-237/train_data.pkl --kbe_data_dir ~/mayank/closed_kbc_data/kg-bert --kge_data_dir ~/mayank/closed_kbc_data/ConvE-complex/ --dataset FB15k-237 --output_dir ~/mayank/closed_kbc_data/data_for_stage2/ConvE-complex-fb15k237 --output_file train_data.txt --model Complex --predictions
python3 tokenize_pkl.py --inp ~/mayank/closed_kbc_data/data_for_stage2/ConvE-complex-fb15k237/mapped_to_ids/entity_id_map.txt --model_str bert-base-cased
python3 tokenize_pkl.py --inp ~/mayank/closed_kbc_data/data_for_stage2/ConvE-complex-fb15k237/mapped_to_ids/relation_id_map.txt --model_str bert-base-cased
